name: Release JSR

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release JSR
    if: github.repository == 'eryue0220/unplugin-stylex'
    permissions:
      contents: read
      pull-requests: write
      id-token: write # The OIDC ID token is used for authentication with JSR.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm build

      - name: Publish JSR
        run: npx jsr publish
